### ISSUE TITLE
TypeError: Object of type date is not JSON serializable

### ISSUE THREAD

**Issue by datakurre** [hh-h/aiohttp-swagger3#17]
When schema has a string field with format type date

 ```
                  date:
                      type: string
                      format: date
                      example: 2019-01-01
```

en exception is raised when rendering SwaggerDocs.

I assume this needs customized JSON serializer instance somewhere to properly turn example date type value into JSON.

```
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/nix/store/kxj94larps9qil0hbx5ca1wg3kngg36h-python3-3.7.4-env/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/nix/store/kxj94larps9qil0hbx5ca1wg3kngg36h-python3-3.7.4-env/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/nix/store/kxj94larps9qil0hbx5ca1wg3kngg36h-python3-3.7.4-env/lib/python3.7/site-packages/aiohttp_swagger3/routes.py", line 12, in _swagger_spec
    return web.json_response(request.app[_SWAGGER_SPECIFICATION])
  File "/nix/store/kxj94larps9qil0hbx5ca1wg3kngg36h-python3-3.7.4-env/lib/python3.7/site-packages/aiohttp/web_response.py", line 715, in json_response
    text = dumps(data)
  File "/nix/store/kxj94larps9qil0hbx5ca1wg3kngg36h-python3-3.7.4-env/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/nix/store/kxj94larps9qil0hbx5ca1wg3kngg36h-python3-3.7.4-env/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/nix/store/kxj94larps9qil0hbx5ca1wg3kngg36h-python3-3.7.4-env/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/nix/store/kxj94larps9qil0hbx5ca1wg3kngg36h-python3-3.7.4-env/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type date is not JSON serializable
```

**Comment by hh-h** [comment]
Hi, what version you use?  
Provide full schema for route, please, because I have test for that case  https://github.com/hh-h/aiohttp-swagger3/blob/master/tests/test_docs_queries.py#L311

**Comment by datakurre** [comment]
@hh-h Thank for fast reply. Version is 0.2.2. I'll figure out minimal example tomorrow.

**Comment by hh-h** [comment]
I missed that you talking about rendering swagger docs, for some reason example section converts to datetime, will fix soon :)

**Comment by hh-h** [comment]
As a workaround, put the date into quotes `2019-01-01 => "2019-01-01"`

**Comment by hh-h** [comment]
Uploaded new version.  
This is wasn't bug actually, but I think that will be a common mistake, so better to handle it :)

**Comment by datakurre** [comment]
Wow, thanks a lot! Even before that I had only good experience about this package :)
