### ISSUE TITLE
content-type can be optional

### ISSUE THREAD

**Issue by hh-h** [hh-h/aiohttp-swagger3#19]
```
Traceback (most recent call last):
  File "start.py", line 120, in error_middleware
    return await handler(request)
  File "start.py", line 115, in validate_token
    return await handler(request)
  File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.7/site-packages/aiohttp_remotes/x_forwarded.py", line 73, in middleware
    return await handler(request)
  File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.7/site-packages/aiohttp/web_urldispatcher.py", line 158, in handler_wrapper
    result = await result
  File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.7/site-packages/aiohttp_swagger3/swagger.py", line 71, in _handle_swagger_call
    kwargs = await route.parse(request)
  File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.7/site-packages/aiohttp_swagger3/swagger_route.py", line 141, in parse
    raw_media_type = request.headers["Content-Type"]
  File "multidict/_multidict.pyx", line 62, in multidict._multidict._Base.__getitem__
  File "multidict/_multidict.pyx", line 57, in multidict._multidict._Base._getone
  File "multidict/_multidict.pyx", line 52, in multidict._multidict._Base._getone
KeyError: 'Content-Type'
```

**Comment by hh-h** [comment]
Closed #21
